lobby:
  world: "hub"
  position: [0.0,67.0,0.0]
game:
  intermission_length: 30
  starting_position: [-0.5,67.0,-0.5]
templates:
  root_path: "templates"
  worlds_path: "worlds"
  obstacles_path: "obstacles"
  game_template_world: "game"